const crearError = (res,  codigo) => {
    const erroresHttp = {
        100: "Continúa",
        101: "Protocolos de conmutación",
        102: "Procesando",
        103: "Primeras pistas",
        200: "OK",
        201: "Creado",
        202: "Aceptado",
        203: "Información no autorizada",
        204: "Sin contenido",
        205: "Restablecer contenido",
        206: "Contenido parcial",
        207: "Multiestado",
        208: "Ya comunicado",
        226: "MI Utilizado",
        300: "Varias opciones",
        301: "Movido permanentemente",
        302: "Encontrado",
        303: "Ver otros",
        304: "No modificado",
        307: "Redireccionamiento temporal",
        308: "Redireccionamiento permanente",
        400: "Bad request",
        401: "No autorizado",
        402: "Pago requerido",
        403: "Prohibido",
        404: "No se ha encontrado",
        405: "Método no permitido",
        406: "No aceptable",
        407: "Se requiere autenticación proxy",
        408: "Tiempo de espera de la solicitud",
        409: "Conflicto",
        410: "Gone",
        411: "Longitud requerida",
        412: "Condición previa fallida",
        413: "Contenido demasiado grande",
        414: "URI demasiado largo",
        415: "Tipo de soporte no compatible",
        416: "Alcance no satisfactorio",
        417: "Expectativa fallida",
        421: "Petición mal dirigida",
        422: "Contenido no procesable",
        423: "Bloqueado",
        424: "Dependencia fallida",
        425: "Demasiado pronto",
        426: "Actualización necesaria",
        428: "Condición previa requerida",
        429: "Demasiadas peticiones",
        431: "Los campos de la cabecera de la solicitud son demasiado grandes",
        451: "No disponible por motivos legales",
        500: "Error interno del servidor",
        501: "No aplicado",
        502: "Bad gateway",
        503: "Servicio no disponible",
        504: "Tiempo de espera de la puerta de enlace",
        505: "Versión HTTP no admitida",
        506: "Variante también negociada",
        507: "Almacenamiento insuficiente",
        508: "Bucle detectado",
        511: "Autenticación de red necesaria"
    };
    
    let mensaje = erroresHttp[codigo] || 'ese error no lo conoce ni dios'

    
    res.send({error: mensaje}) 
}
module.exports = {crearError}